### ISSUE TITLE
Created and Scheduled timings don't match what is in the backend.

### ISSUE THREAD

**Issue by blancmatter** [TOMToolkit/tom_base#426] opened 2021-02-23 17:53 UTC
**Describe the bug**
When viewing observations (either in the Observations Page, or the Observations Tab of the target page), the timings for the scheduled and created never seem to macth what is held in the `tom_observations_observationrecord` table.

The Date and Hour are correct, however the minutes and seconds always get forced to 2 minutes past the hour.

**To Reproduce**
1. Go to Observations page
2. Click on Update Observation Status
3. Observe that the timings are all forced to 2 minutes past the hour.

Interestingly I entered a date in the Backend from 2009 and it changed the behaviour in setting the minutes to 08 minutes past the hour (I think). 

**Expected behavior**
The Date and Time should match the fields in the tom_observations_observationrecord table.

**Screenshots**
![tom_dateissue](https://user-images.githubusercontent.com/45846630/108885359-a036fa80-75ff-11eb-9a2e-867fdf8277f5.png)

Here the created Field should be studied, but also this happens with scheduled_start and scheduled_end.

**Desktop (please complete the following information):**
- OS - Ubuntu 18.04
- Browser - Firefox
- Version - Latest tom toolkit 2.4.2?
- Python Version - 3.6.9

**Comment by dmcollom** [comment] 2021-03-09 04:26
Can you give me some information about where these observations came from? Created manually, pulled from somewhere, anything? I'd even appreciate a data dump--you can do so with ``./manage.py dumpdata -o obs_data.json tom_observations``.

I just did some digging in my local and all of my datetimes are on the up and up. Even imported some LCO observations and was still unable to reproduce this.

**Comment by dmcollom** [comment] 2021-05-07 23:08
I'm going to close this for now--feel free to re-open this with some more information if you experience it again.

**Closed by dmcollom** 2021-05-07 23:08 UTC
Labels: bug
