### ISSUE TITLE
App to interactively add spectral lines to Spectroscopy plots 

### ISSUE THREAD

**Issue by jchate6** [TOMToolkit/tom_base#935] opened 2024-05-20 17:49 UTC
Saguaro TOM would like to incorporate the SNEX2 capability to use plotly to add certain spectral lines to spectroscopy plots.

See https://github.com/LCOGT/snex2/blob/master/custom_code/dash_apps/spectra.py

**Comment by jchate6** [comment] 2024-05-29 17:59
@griffin-h @cmccully 
Can you please add comments describing the specific issues you ran into trying to implement this?

**Comment by griffin-h** [comment] 2024-05-29 18:38
Possibly a duplicate of #861?

**Closed** 2024-05-31 17:50 UTC
Labels: enhancement, User
