### ISSUE TITLE
Cannot update targets using TargetUpdateView

### ISSUE THREAD

**Issue by griffin-h** [TOMToolkit/tom_base#663] opened 2023-05-20 18:33 UTC
**Describe the bug**
When I try to update a Target attribute using the TargetUpdateView, I get an error saying that "Target with Name or alias similar to _____ already exists." It's as if the TOM is trying to create a new target instead of update the existing target.

**To Reproduce**
1. Go to a target detail page
2. Click on 'Update'
3. Modify any value
4. Click on 'Save'
5. See error

**Expected behavior**
After clicking 'Save' the TOM should redirect to the target detail page and the target should have updated attributes.

**Desktop (please complete the following information):**
- OS: Ubuntu
- Browser: Firefox 113.0.1
- Python Version 3.10.11
- Django Version 2.4
- TOM Toolkit Version 2.14.3

**Additional context**
I am using the strict match manager for target names suggested in the TOM Toolkit documentation. Not sure if this is related.

**Comment by jchate6** [comment] 2023-06-27 23:47
@griffin-h I cannot reproduce this. 
I've have added a strict match manager and tried to run it locally as well as writing tests to do so. 

In theory the strict match manager should be MORE forgiving, not less. 

My guess is that the target you are trying to update has a name or an alias in common with the name of another target already in the DB that was present before the match manager was in place. (Or you saved things without doing a `full_clean` and bypassed the match manager all together.)

The `update` doesn't know the difference between the old information and the new information and will validate on everything, raising an error because the old name matches another object in the DB.

Can you do a quick DB check (`Target.matches.check_for_fuzzy_match('target_name')` and `Target.matches.check_for_fuzzy_match('alias_name')`) to see if you have repeats already in the DB?

If you only get back one result in those querysets I'll need to look more into it. Otherwise if you get multiple results I can try to figure out a way to bypass the validation for established data...

**Comment by griffin-h** [comment] 2023-06-27 23:55
@jchate6 I don't think this can be the problem, because I get this behavior if I update any field (e.g., distance), not just alias. But to be sure, I ran your suggestions and got only 1 match for the target name and 0 matches for an alias.

```
In [5]: Target.matches.check_for_fuzzy_match('AT2023lxu')
Out[5]: <QuerySet [<Target: AT2023lxu>]>

In [6]: Target.matches.check_for_fuzzy_match('ZTF23aaptsuy')
Out[6]: <QuerySet []>
```

I think the problem is that the update form is trying to save the target as a new target, rather than updating the existing target. The ___ in my initial example is the target name itself (it has no aliases).

**Comment by jchate6** [comment] 2023-06-28 00:14
I'm not sure why your TOM would be making new targets from the update page when tom_base does not. 
Let me dig a little deeper and see what I can find.

**Comment by jchate6** [comment] 2023-06-30 21:51
A fix for this is under review and will hopefully be released soon.

**Closed** 2023-06-30 22:23 UTC
Labels: bug
